config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "transactions#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_scope :user do
    resources :users
  end

  resources :transactions
  post 'transactions/update_group_status', to: 'transactions#update_group_status', as: 'update_group_status_transactions'
  resources :expenses
  resources :groups
  resources :incomes
  resources :goals do
    member do
      patch :favorite
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
  has_many :transactions, through: :users

  # scope :expenses, -> { transactions.where(kind: "Expense", group_status: false)}

  def expenses
    Transaction.where(group: self, kind: "Expense", group_status: false)
  end

  def settled_expenses
    Transaction.where(group: self, kind: "Expense", group_status: true)
  end

  def who_to_who
    debitors = user_amounts_diff.select { |hash| hash[:divided_amount].negative? }
    creditors = user_amounts_diff.select { |hash| hash[:divided_amount].positive? }
    transactions_to_settle = []

    creditors.each_with_index do |creditor, creditor_index|
      debitors.each_with_index do |debitor, debitor_index|

        next if debitor[:amount] == 0

        amount = [debitor[:amount].abs, creditor[:amount]].min

        debitors[debitor_index][:amount] += amount
        creditors[creditor_index][:amount] -= amount

        transactions_to_settle << {
          expense: Transaction.new(
            name: "Settlement to #{creditor[:user].username.capitalize}",
            amount: amount,
            kind: "Expense",
            group: self,
            category: "Settlement",
            user: debitor[:user],
            group_status: true,
            ),
          income: Transaction.new(
            name: "Settlement from #{debitor[:user].username.capitalize}",
            amount: amount,
            kind: "Income",
            group: self,
            category: "Settlement",
            user: creditor[:user],
            group_status: true,
            ),
          receiver: creditor[:user],
          payer: debitor[:user],
        }

        break if creditors[creditor_index][:amount] == 0
      end
    end

    transactions_to_settle
  end

  def total
    expenses.sum(:amount)
  end

  def settled_total
    settled_expenses.sum(:amount)
  end

  def fair_amount
    @fair_amount = total / users.count
  end

  def total_expenses_of(user)
    expenses.where(user: user).sum(:amount)
  end

  def user_amounts_diff
    users.map do |user|
      full_amount = total_expenses_of(user)
      amount = (total_expenses_of(user) - fair_amount)
      {
        user: user,
        amount: amount,
        divided_amount: amount / users.count,
        full_amount: full_amount,
      }
    end
  end




  def user_amounts
    @user_amounts = expenses.group(:user).sum(:amount)
  end

  # def no_expense_users
  #   @no_expense_users = @group.users.select { |user| user.transactions.where(kind: "Expense", group_status: false, group_id: @group).empty? }
  # end

  # def who_to_who
  #   @divided_user_amounts = @user_amounts.transform_values { |value| value / @group.users.count }
  #   @current_user_divided_amount = {}
  #   @current_user_divided_amount = @divided_user_amounts.extract!(current_user.email)
  #   @divided_user_amounts.delete(current_user.email)
  # end

  # def hash
  #   settlement_arr= [
  #     {transaction: Transaction.new(amount: 100 , kind: "Expense", group: self, category: "Settlement", user_id: 1, group_status: true), receiver: user2}
  #   ]

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def show
    @groups = current_user.groups
    @group = Group.find(params[:id])
    @group_expenses= @group.expenses
    if !current_user.groups.exists?(@group.id)
      redirect_to groups_path
    end
    @expenses = Transaction.where(group: @group, kind: "Expense")
    @settled_group_expenses= @group.transactions.where(group_id: @group.id, kind: "Expense", group_status: true)
    @donut_chart_group = Transaction.where(group_id: @group, kind: "Expense", group_status: false).group(:category).sum(:amount)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    user_ids = params[:group][:user_ids]
    friends = User.where(id: user_ids)

    friends.each do |friend|
      @group.users << friend
    end

    @group.users << current_user

    if @group.save
      redirect_to groups_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    user_ids = params[:group][:user_ids]
    friends = User.where(id: user_ids)
    friends.each do |friend|
    @group.users << friend if !@group.users.include?(friend)
    end
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, user_groups_attributes: [:user_id])
  end

end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, placeholder: 'Group Name', input_html: { class: 'rounded-boxes' } %>
    <%= f.input :user_ids, label: "Usernames", collection: User.where.not(id: current_user.id).pluck(:username, :id), input_html: { multiple: true, class: 'multiple-select rounded-boxes', style: 'border-radius: 0.5em;', data: { controller: 'tom-select', tom_select_options_value: { tags: true } } }, wrapper_html: { class: 'rounded-boxes', data: { allow_clear: true } } %>
    <div class="form-actions d-flex justify-content-between mt-4">
      <div class="d-flex align-items-center">
        <%= link_to "Cancel", groups_path, class: "ms-3 btn btn-flat-cancel" %>
      </div>
      <div>
        <%= f.button :submit, class: "btn btn-flat" %>
      </div>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="container mt-5 mb-5" style="width: 400px">
  <h1>Edit Group</h1>

  <%= render "form", group: @group %>

</div>

app/views/groups/index.html.erb
<div class="container">
  <div>
    <div class="d-flex justify-content-between mt-3 mb-3">
      <h3>Your Groups</h3>
<%= link_to new_group_path, class: "btn btn-flat" do %>
  <i class="fas fa-people-group"></i>
<% end %>    </div>


    <% if @groups.empty? %>
      <p>You haven't created a group yet!</p>
    <% else %>
      <% @groups.each do |group| %>
                <div class="card-product mb-3 d-flex">
                  <div class="col-5">
                    <p class="fs-6 ms-3"><%= group.name.capitalize %></p>
                  </div>
                  <div class="col-4 d-flex justify-content-end">
                    <p class="fs-8 ms-3">
                      <div class="container-avatar">
                          <% group.users.each do |user| %>
                              <% if user.photo.attached? %>
                                <%= image_tag(user.photo, class: "avatar", style: "height: 25px; width: 25px; border-radius: 50%", data_controller:"tooltip", data_bs_toggle:"tooltip", data_bs_placement:"top", title: "#{user.username.capitalize}") %>
                              <% else %>
                                <i class="fa-solid fa-circle-user text-dark fs-2"></i>
                              <% end %>
                          <% end %>
                       </div>
                    </p>
                  </div>
                  <div class="col-2 d-flex me-2">
                  <%= link_to "Open", group_path(group),
                    class: "btn btn-flat" %></div>
                </div>
              <% end %>
    <% end %>
</div>

app/views/groups/new.html.erb
<div class="container">
  <h1>New Group</h1>

  <%= render "form", group: @group %>

</div>

app/views/groups/show.html.erb
<div class="container">
  <div class="d-flex justify-content-between">
    <h3><%= @group.name  %>'s Expenses</h3>
    <div class="dropdown">
        <button class="dropbtn"><i class="fa-solid fa-ellipsis-vertical"></i></button>
          <div class="dropdown-content">
            <%= link_to "Edit Group", edit_group_path(@group)%>
            <%= link_to "Delete Group",
              group_path(@group),
              method: :delete,
              data: { turbo_method: 'DELETE', turbo_confirm: "Delete #{@group.name} group with all its expenses?" }%>
          </div>
    </div>
  </div>

  <div>
  <% if @group.expenses.empty? && @group.settled_expenses.empty? %>
    <p>Your group hasn't spent any money!</p>
    <%= link_to "Add your first expense to #{@group.name}!", new_transaction_path, class: "btn btn-flat" %>

  <% else %>


  <% if !@group.expenses.empty? %>
    <div class="d-flex mb-3"><%= render "shared/donut_chart", data: @donut_chart_group %></div>
      <div class="row">
        <div class="col-md-6">
          <div class="card bg-white text-black mb-2 rounded" style="border-radius: 5px!important">
            <div class="card-body">
              <h5 class="card-title fw-bold"><i class="fa-solid fa-receipt"></i> Totals:</h5>
              <% @group.user_amounts_diff.each do |el| %>
                <p class="card-text"><%= "- #{el[:user].username} spent #{el[:full_amount]} €" %></p>
              <% end %>
              <h5 class="card-title fw-bold"><i class="fa-solid fa-handshake"></i> Fair Share: <%= @group.fair_amount.round(1) %> €</h5>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card bg-white text-black mb-4 rounded" style="border-radius: 5px!important">
            <div class="card-body">
              <h5 class="card-title fw-bold"><i class="fa-solid fa-file-invoice"></i> Who owes:</h5>
              <% @group.who_to_who.each do |txn| %>
                <p class="card-text"><%= "- #{txn[:payer].username} owes #{txn[:receiver].username} #{txn[:expense].amount.round(1)} €" %></p>
              <% end %>
              <%= form_tag update_group_status_transactions_path, method: :post do %>
                <%= hidden_field_tag :group_id, @group.id %>
                <div class="d-flex justify-content-end border-white">
                  <%= submit_tag "Settle & Pay", class: "btn btn-flat" %>
                </div>
              <% end %>
            </div>
          </div>
</div>


</div>

</div>


    <div>
      <div>
        <h5 class="font-weight-bold">Total Expenses: <%= @group.total %> € <i class="fa-solid fa-circle-question fa-2xs" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="These expenses are not settled yet"></i></h5>
      </div>

      <div class=" d-flex flex-column-reverse">
               <% @group_expenses.each do |expense| %>
                <div class="card-product mb-3 d-flex">
                  <div class="col-1 ms-3 d-flex">
                    <div>
                      <% if expense.user.photo.attached? %>
                        <%= image_tag(expense.user.photo, class: "avatar", style: "height: 25px; width: 25px; border-radius: 50%", data_controller:"tooltip", data_bs_toggle:"tooltip", data_bs_placement:"top", title: "#{expense.user.username.capitalize}") %>
                      <% else %>
                        <i class="fa-solid fa-circle-user text-dark fs-2"></i>
                      <% end %>
                    </div>
                  </div>
                  <div class="col-3 d-flex">
                    <p class="fs-12 ms-1 "><%= expense.name.capitalize %></p>
                  </div>

                  <div class="col-3 d-flex">
                    <p class="fs-8"><%= expense.category %></p>
                  </div>
                  <div class="col-2 d-flex justify-content-end">
                    <p class="fs-8"><%= expense.amount.round(1) %> € <i class="fa-solid fa-circle-info" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="<%= expense.created_at.strftime('%A, %d %b %Y %l:%M %p') %>"></i></p>
                  </div>
                  <div class="col-2 d-flex justify-content-end">
                    <div class="dropdown">
                      <button class="dropbtn me-2"><i class="fa-solid fa-ellipsis-vertical"></i></button>
                        <div class="dropdown-content">
                          <%= link_to "Edit", edit_transaction_path(expense)%>
                          <%= link_to "Delete",
                            transaction_path(expense),
                            method: :delete,
                            data: { turbo_method: 'DELETE', turbo_confirm: "Delete #{expense.name} group with all its expenses?" }%>
                        </div>
                    </div>
                  </div>
                </div>
              <% end %>
        </div>
    <% end %>


    <h5 class="mt-3 font-weight-bold text-muted">Total Settled Expenses: <%= @group.settled_total.round(1) %> € <i class="fa-solid fa-circle-question fa-2xs" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="These expenses have been settled"></i></h5>
    <div class=" d-flex flex-column-reverse">
               <% @settled_group_expenses.each do |expense| %>
                <div class="card-product bg-light text-muted mb-3 d-flex">
                  <div class="col-1 ms-3 d-flex">
                    <div>
                      <% if expense.user.photo.attached? %>
                        <%= image_tag(expense.user.photo, class: "avatar", style: "height: 25px; width: 25px; border-radius: 50%", data_controller:"tooltip", data_bs_toggle:"tooltip", data_bs_placement:"top", title: "#{expense.user.username.capitalize}") %>
                      <% else %>
                        <i class="fa-solid fa-circle-user text-dark fs-2"></i>
                      <% end %>
                    </div>
                  </div>
                  <div class="col-3 d-flex">
                    <p class="fs-12 ms-1 "><%= expense.name.capitalize %></p>
                  </div>

                  <div class="col-3 d-flex">
                    <p class="fs-8"><%= expense.category %></p>
                  </div>
                  <div class="col-2 d-flex justify-content-end">
                    <p class="fs-8"><%= expense.amount.round(1) %> € <i class="fa-solid fa-circle-info" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="<%= expense.created_at.strftime('%A, %d %b %Y %l:%M %p') %>"></i></p>
                  </div>
                  <div class="col-2 d-flex ">
                    <p class="fs-8 ms-3" >Settled <i class="fa-solid fa-square-check"></i></p>
                  </div>
                </div>
              <% end %>
        </div>
    </div>
  <% end %>
</div>
</div>