config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "transactions#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_scope :user do
    resources :users
  end

  resources :transactions
  post 'transactions/update_group_status', to: 'transactions#update_group_status', as: 'update_group_status_transactions'
  resources :expenses
  resources :groups
  resources :incomes
  resources :goals do
    member do
      patch :favorite
    end
  end
end

app/views/shared/_area_chart.html.erb
<%= area_chart [
  {
    name: 'Balance',
    data: data,
  }
],
    {
      style: "margin-top: -1.58em; z-index: 0;",
      toolbox: {},
      height: "400px;",
      areaStyle: {
        opacity: 1.8,
    }
    }

%>

app/views/shared/_avatars_group.html.erb
<div class="container-avatar">
<img class="avatar" alt="avatar" src="https://avatars.githubusercontent.com/u/131615474?v=4" />
<img class="avatar" alt="avatar" src="https://avatars.githubusercontent.com/u/131250939?v=4" />
<img class="avatar" alt="avatar" src="https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1682334219/jiszwkf1k3ossxj6j1rr.jpg" />
<img class="avatar" alt="avatar" src="https://avatars.githubusercontent.com/u/118752990?v=4" />
</div>

app/views/shared/_button_flying.html.erb
<button type="submit" class="button-upload" routerLink="/users/sign_in">
	<span class="button-upload__text">Login</span>
  <svg
		xmlns="http://www.w3.org/2000/svg"
		width="40.089"
		height="1em"
		class="button-upload__logo"
		viewBox="0 0 576 512"
	>

		<g
			transform="translate(26.150) rotate(49)"
			class="button-upload__logo--complete"
		>
			<g
				transform="translate(5.976 28.664)"
				class="button-upload__logo--trails"
			>
				<path
					d="d="M0 112.5V422.3c0 18 10.1 35 27 41.3c87 32.5 174 10.3 261-11.9c79.8-20.3 159.6-40.7 239.3-18.9c23 6.3 48.7-9.5 48.7-33.4V89.7c0-18-10.1-35-27-41.3C462 15.9 375 38.1 288 60.3C208.2 80.6 128.4 100.9 48.7 79.1C25.6 72.8 0 88.6 0 112.5zM288 352c-44.2 0-80-43-80-96s35.8-96 80-96s80 43 80 96s-35.8 96-80 96zM64 352c35.3 0 64 28.7 64 64H64V352zm64-208c0 35.3-28.7 64-64 64V144h64zM512 304v64H448c0-35.3 28.7-64 64-64zM448 96h64v64c-35.3 0-64-28.7-64-64z""
					transform="translate(-153.97 -738.46)"
					fill="#fafafa"
				/>
				<path
					d="M337.1,738.46l-1.692.055v6.115l1.692-1.147"
					transform="translate(-328.367 -738.46)"
					fill="#fafafa"
				/>
				<path
					d="M243.98,738.46h1.692V747l-.846.939-.846-.971"
					transform="translate(-240.486 -738.46)"
					fill="#fafafa"
				/>
			</g>
			<g class="button-upload__logo--rocket">
				<path
					d="M0 112.5V422.3c0 18 10.1 35 27 41.3c87 32.5 174 10.3 261-11.9c79.8-20.3 159.6-40.7 239.3-18.9c23 6.3 48.7-9.5 48.7-33.4V89.7c0-18-10.1-35-27-41.3C462 15.9 375 38.1 288 60.3C208.2 80.6 128.4 100.9 48.7 79.1C25.6 72.8 0 88.6 0 112.5zM128 416H64V352c35.3 0 64 28.7 64 64zM64 224V160h64c0 35.3-28.7 64-64 64zM448 352c0-35.3 28.7-64 64-64v64H448zm64-192c-35.3 0-64-28.7-64-64h64v64zM384 256c0 61.9-43 112-96 112s-96-50.1-96-112s43-112 96-112s96 50.1 96 112zM252 208c0 9.7 6.9 17.7 16 19.6V276h-4c-11 0-20 9-20 20s9 20 20 20h24 24c11 0 20-9 20-20s-9-20-20-20h-4V208c0-11-9-20-20-20H272c-11 0-20 9-20 20z"
					fill="#fafafa"
				/>
			</g>
		</g>
	</svg>
</button>

app/views/shared/_card_submit.html.erb
<div class="modal-form">
   <div class="wrapper">
    <form class="form-submit">
      <h2 class="form-submit-heading">Add expenses</h2>
      <input type="text" class="form-control" name="amount" placeholder="Amount" required="" autofocus="" />
    <select class="form-submit-heading" name="category" onchange="showHide(this)">
      <option>Select a category</option>
      <option value="restaurant">Restaurant</option>
      <option value="cinema">Cinema</option>
      <option value="other">Other</option>
    </select>

  <div class="dropdown-options">
    <div class="show-hide" id="restaurant">
    </div>
    <div class="show-hide" id="cinema">
    </div>
    <div class="show-hide" id="other">
    </div>
  </div>
  <select class="form-submit-heading" name="category" onchange="showHide(this)">
    <option>Frequency</option>
    <option value="always">Always</option>
    <option value="rarely">rarely</option>
    <option value="other">Other</option>
    </select>
   <div class="dropdown-options">
    <div class="show-hide" id="always">
    </div>
    <div class="show-hide" id="rarely">
    </div>
    <div class="show-hide" id="other">
    </div>
  </div>
  </div>
       <button class="btn">Submit</button>
    </form>
  </div>
</div>

app/views/shared/_donut_chart.html.erb
<%= donut_chart data,
  class: 'box',
  height: "450px",
  width: "780px",
  style: "margin-top: -4.7em; z-index: 0;",

  options: {
    legend: {
      bottom: '0',
      textStyle: {

      }
    },
    emphasis: {
      itemStyle: {
        shadowBlur: 10,
        shadowOffsetX: 0,
        shadowColor: 'rgba(0, 0, 0, 0.5)'
      }
    }
  }
%>

app/views/shared/_favorite_goal.html.erb
<h3 class="text-center"><%= @favorite_array.first.name %></h3>

<div class="row justify-content-center">
  <div class="col-8 col-sm-6">
    <% if @favorite_array.first.photo.attached? %>
      <%= cl_image_tag @favorite_array.first.photo.key, class:"img-fluid mx-auto d-block rounded-4", style: "width: 150px; max-height: 100px;"%>
    <% else %>
      <img src="https://m.media-amazon.com/images/I/716+A9OrcSL._AC_SL1500_.jpg" class= "img-fluid mx-auto d-block rounded-4" alt="" style="width: 150px; max-height: 100px;">
    <% end %>
  </div>
</div>

<div class="shadow-progress" style="border-radius: .5em;">
  <div class="progress mt-4 mb-2" style="height: 30px; border-radius: .5em;">
    <div class="progress-bar bg-success" role="progressbar" style="width: <%= @percentage %>%; border-radius: .5em;" aria-valuenow="<%= @percentage %>" aria-valuemin="0" aria-valuemax="100"><%= @percentage.round(1) %>%</div>
  </div>
</div>
<div class="d-flex justify-content-between">
  <% if current_user.balance < 0 %>
    <p><strong>Saved: </strong><span class="text-danger"><%= current_user.balance.round(1) %> €</span></p>
  <% else %>
    <p><strong>Saved: </strong><span class="text-success"><%= current_user.balance.round(1) %> €</span></p>
  <% end %>
    <p></p><strong><%= @goals.first.name %>'s Price:<strong> <span class=""><%= @goals.first.amount.round(1) %> €</span></p>
</div>

<div class="d-flex justify-content-end mt-3 mb-3">
  <%= link_to new_goal_path, class: "btn  btn-flat" do %>
  <i class="fa-solid fa-plus me-2"></i><i class="fa-solid fa-trophy fs-4"></i>
  <% end %>
</div>
<% @goals.each do |goal| %>
  <% percentages = (current_user.balance * 100) / goal.amount %>
  <div style="border-radius: .5em .5em 0 0;">
    <div class="progress" style="height: 5px; max-width: 100%; border-radius: .5em .5em 0 0;">
      <div class="progress-bar bg-success" role="progressbar" style="width: <%= percentages %>%;" aria-valuenow="<%= percentages %>" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    </div>
  <div class="card-product d-flex mb-3" style="border-radius: 0 0 .5em .5em;">
      <% if goal.photo.attached? %>
        <%= cl_image_tag goal.photo.key, style: "border-radius: 0 0 0 .5em;" %>
      <% else %>
        <img src="https://m.media-amazon.com/images/I/716+A9OrcSL._AC_SL1500_.jpg">
      <% end %>
    <div class="col-3 d-flex justify-content-start">
      <p class="fs-8 ms-1 me-3"><%= goal.name %></p>
    </div>
    <div class="col-3 d-flex justify-content-end">
      <p class="fs-8 me-3"><%= goal.amount.round(1) %> € <i class="fa-solid fa-circle-info" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="<%= goal.created_at.strftime('%A, %d %b %Y %l:%M %p') %>"></i></p>
    </div>
    <div class="d-flex">
      <%= link_to favorite_goal_path(goal), data: { turbo_method: :patch } do %>
        <% if goal.favorite == false %>
          <i class="fa-regular fa-star fs-4 mt-1 me-3 text-dark"></i>
        <% else %>
          <i class="fa-solid fa-star fs-4 mt-1 me-3 text-success"></i>
        <% end %>
      <% end %>
      <div class="dropdown">
        <button class="dropbtn me-2"><i class="fa-solid fa-ellipsis-vertical"></i></button>
          <div class="dropdown-content">
            <%= link_to "Edit", edit_goal_path(goal)%>
            <%= link_to "Delete",
              goal_path(goal),
              method: :delete,
              data: { turbo_method: 'DELETE', turbo_confirm: "Delete #{goal.name} group with all its expenses?" }%>
          </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon ">
  <div class="container-fluid">
    <div class="navbar-brand d-flex align-items-center">
      <%= link_to root_path, class: "navbar-brand" do %>
        <i class="fa-solid fa-wallet fs-1" style="color: black; margin-left: 20px; margin-right: 6px;"></i>
      <% end %>
      <p class="mt-1" style="margin-bottom: 3px!important;">
      <span class="d-flex align-center">
      <% if current_user.balance < 0 %>
        <strong>Balance: </strong><span class="text-danger ms-1" style="margin-top: 1.6px;"><%= current_user.balance.round(1) %> €</span></span></p>
      <% else %>
        <strong>Balance: </strong><span class="text-success ms-1" style="margin-top: 1.6px;"><%= current_user.balance.round(1) %> €</span></span></p>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_message_popup.html.erb
<div class="modal">
  <p class="message">You added 1000€</p>
  <div class="options">
    <button class="btn">Close</button>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar fixed-bottom navbar-light container-fluid justify-content-center">

    <div class="container-icons">
    <div class="border-bar"></div>
  <ul class="navbar-nav">
      <li class="nav-item me-3 me-lg-1 mr-5 mb-4">
        <a class="nav-link">
        <div class="icon-wrapper">
            <%= link_to root_path do %>
              <% content_tag(:i, "", class: "fa-solid fa-house text-dark") %>
            <% end %>
            <div class="name-icons">
              <p>Home</p>
            </div>
          </div>
        </a>
      </li>

      <li class="nav-item me-3 me-lg-1 mr-5 mb-4">
        <a class="nav-link">
        <div class="icon-wrapper">
            <%= link_to goals_path do %>
              <% content_tag(:i, "", class: "fa-solid fa-trophy text-dark") %>
            <% end %>
            <div class="name-icons">
              <p>Goals</p>
            </div>
          </div>
        </a>
      </li>

      <li class="nav-item me-3 me-lg-1 mr-5 mb-4">
        <a class="nav-link">
            <div class="icon-wrapper">
              <%= link_to new_transaction_path do %>
                <% content_tag(:i, "", class: "fa-regular fa-square-plus text-dark") %>
              <% end %>
              <div class="name-icons">
                <p>Add</p>
            </div>
          </div>
        </a>
      </li>

      <li class="nav-item me-3 me-lg-1 mr-5 mb-4">
        <a class="nav-link">
          <div class="icon-wrapper">
            <%= link_to groups_path do %>
              <% content_tag(:i, "", class: "fa-solid fa-people-group text-dark") %>
            <% end %>
            <div class="name-icons">
              <p>Groups</p>
            </div>
          </div>
        </a>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item me-3 me-lg-1 mr-5 mb-4">
          <a class="nav-link" href="/users/">
            <div class="icon-wrapper">
              <%= link_to user_path(current_user) do %>
                <% if current_user.photo.attached? %>
                  <%= image_tag(current_user.photo, class: "avatar", style: "height: 30px; width: 30.5px; rounded-circle; border: 2px solid #000000bd;") %>
                <% else %>
                  <% content_tag(:i, "", class: "fa-solid fa-circle-user text-dark") %>
                <% end %>
              <% end %>
              <div class="name-icons">
                <p>Profile</p>
              </div>
            </div>
          </a>
        </li>
      <% end %>

  </ul>
  </div>
</nav>

app/views/shared/_popup.html.erb
<div class="body-pop">
  <div class="modal">
    <p class="message">Do you want to confirm ?</p>
    <div class="options">
      <button class="btn">Yes</button>
      <button class="btn">No</button>
    </div>
  </div>
</div>

app/views/shared/_popup_choice.html.erb
<div class="body-pop">
  <div class="modal">
    <p class="message">Income or expense?</p>
    <div class="options">
      <%= link_to "Income", new_income_path, class: "btn btn-success" %>
      <%= link_to "Expense", new_expense_path, class: "btn btn-success"%>
    </div>
  </div>
</div>

app/views/shared/_switch_fade.html.erb
<div class="radio-input">
  <label>
  <input type="radio" id="value-1" name="value-radio" value="value-1">
  <span>Option 1</span>
  </label>
  <label>
    <input type="radio" id="value-2" name="value-radio" value="value-2">
  <span>Option 2</span>
  </label>
  <label>
    <input type="radio" id="value-3" name="value-radio" value="value-3">
  <span>Option 3</span>
  </label>
  <span class="selection"></span>
</div>