config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "transactions#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_scope :user do
    resources :users
  end

  resources :transactions
  post 'transactions/update_group_status', to: 'transactions#update_group_status', as: 'update_group_status_transactions'
  resources :expenses
  resources :groups
  resources :incomes
  resources :goals do
    member do
      patch :favorite
    end
  end
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :user
  belongs_to :group, optional: true

end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController

  def index
    @incomes = Income.where(user: current_user)
  end

  def show
    @income = Income.find(params[:id])
    if @income.user == current_user
      redirect_to income_path(income)
    else
      redirect_to incomes_path
    end
  end

  def new
    @income = Income.new
  end

  def create
    @income = Income.new(income_params)
    @income.user = current_user
    if @income.save
      redirect_to incomes_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @income = Income.find(params[:id])
  end

  def update
    @income = Income.find(params[:id])
    if @income.update(income_params)
      redirect_to incomes_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @income = Income.find(params[:id])
    @income.destroy
    redirect_to incomes_path
  end

  private

  def income_params
    params.require(:income).permit(:amount, :category, :name, :frequency)
  end
end

app/views/incomes/_form.html.erb
<%= simple_form_for(@income) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, placeholder: 'income name' %>
    <%= f.input :category, as: :select, collection: ['Salary', 'Investments', 'Rental Income', 'Freelance'],
                   prompt: 'Select Category'%>
    <%= f.input :amount, placeholder: "0,00 €" %>
    <%= f.input :frequency, as: :select, collection: ['One-Time', 'Weekly', 'Monthly'],
                          prompt: 'One-time, Weekly or Monthly' %>
    <div class="form-actions d-flex justify-content-between mt-4">
      <div class="d-flex align-items-center">
        <%= link_to "Cancel", incomes_path, class: "btn btn-danger" %>
      </div>
      <div>
        <%= f.button :submit, class: "btn btn-success" %>
      </div>
    </div>
  </div>

<% end %>

app/views/incomes/edit.html.erb
<div class="container mt-5 mb-5" style="width: 400px">
  <h1>Edit Income</h1>

  <%= render "form", income: @income %>

</div>

app/views/incomes/index.html.erb
<div class="container">
  <h3>Incomes</h3>
  <% if @incomes.empty? %>
    <h5>You haven't added any income yet!</h5>
    <%= link_to "Add your first Income!", new_income_path, class: "btn btn-success" %>
  <% else %>
    <div>
      <%= donut_chart Income.where(user: current_user).group(:category).sum(:amount),
        class: 'box',
        height: "250px",
        width: "600px",
        options: {
          legend: {
            orient: 'vertical', right: 'right',
            height: "250px",
            width: "250px",
          },
          emphasis: {
            itemStyle: {
              shadowBlur: 10,
              shadowOffsetX: 0,
              shadowColor: 'rgba(0, 0, 0, 0.5)'
            }
          }
        }
      %>
    </div>
    <div>
      <% total = 0 %>
      <% @incomes.each do |income| %>
        <% total += income.amount %>
      <% end %>
      <div class="d-flex justify-content-between">
        <h5 class="font-weight-bold">Total Incomes $<%= total %></h5>
        <%= link_to "Add Income", new_income_path, class: "btn btn-success" %>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Category</th>
            <th scope="col">Amount(€)</th>
          </tr>
        </thead>
        <tbody>
          <% @incomes.each do |income| %>
            <tr>
                <td class="font-weight-bold"><%= income.name.capitalize %></td>
                <td class="text-secondary "><%= income.category.capitalize %></td>
                <td class="text-secondary"><%= income.amount %> € <i class="fa-solid fa-circle-info" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="<%= income.created_at.strftime('%A, %d %b %Y %l:%M %p') %>"></i></td>
                <td><%= link_to "Edit", edit_income_path(income),
                class: "btn btn-success"%>
                </td>
                <td><%= link_to "Delete", income_path(income), method: :delete,
                data: { turbo_method: 'DELETE', turbo_confirm: "Delete #{income.name} income?" },
                class: "btn btn-danger" %>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/incomes/new.html.erb
<div class="container mt-5 mb-5" style="width: 400px;">
  <h1>New Income</h1>

  <%= render "form", income: @income %>

</div>